site_name: SPM-iOS
use_directory_urls: false

nav:
- Introducción : 'sesion00/sesion00-introduccion.md'
- Firma, aprovisionamiento y distribución de apps : 'sesion01/sesion01-firma-aprovisionamiento.md'
- Notificaciones Push : 'sesion02/sesion02-notificaciones.md'

theme:
    language: es
    name: 'material'
    palette:
        primary: 'Teal'
        accent: 'Teal'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
    logo: 'imagenes/logo.png'

markdown_extensions:
    - admonition
    - codehilite:
        linenums: true
    - footnotes
    - meta
    - sane_lists
    - toc:
       permalink: true
       toc_depth: 3
    - pymdownx.superfences
