site_name: SPM-iOS
use_directory_urls: false

nav:
- 'Teoría':
#    - 0. Introducción : 'teoria/tema0-introduccion-servicios-ios/introduccion-servicios-ios.md'-->
    - 1. Firma, aprovisionamiento y distribución de apps: 'teoria/tema1-firma-aprovisionamiento/firma-aprovisionamiento.md'
    - 2. Mapas y localización: 'teoria/tema4-mapas-localizacion/mapas-localizacion.md'
    - 3. Notificaciones: 'teoria/tema2-notificaciones/notificaciones.md'
#    - 3. iCloud y CloudKit: 'teoria/tema3-icloud/icloud.md'
#    - 5. Extensiones: 'teoria/tema5-extensiones/extensiones.md'
#    - 6. Anuncios: 'teoria/tema6-anuncios/anuncios.md'
#    - 7. Compras InApp: 'teoria/tema7-compras-in-app/compras-in-app.md'
- 'Prácticas':
    - Práctica 1: 'practicas/practica1/practica1-firma-aprovisionamiento.md'
    - Práctica 2: 'practicas/practica4/practica4-mapas-localizacion.md'
    - Práctica 3: 'practicas/practica2/practica2-notificaciones.md'
#    - Práctica 3: 'practicas/practica3/practica3-icloud.md'
#    - Práctica 5: 'practicas/practica5/practica5-extensiones.md'
#    - Práctica 6: 'practicas/practica6/practica6-anuncios.md'

theme:
    language: es
    name: 'material'
    palette:
        primary: 'Teal'
        accent: 'Teal'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
    logo: 'imagenes/logo.png'

# Ponemos como idioma de búsqueda el inglés
# para conseguir que busque correctamente
# todas las palabras en castellano, sin eliminar
# los excesivos derivados que se definen en
# https://github.com/MihaiValentin/lunr-languages/blob/master/lunr.es.js

extra:
    search:
        language: 'en'

markdown_extensions:
    - admonition
    - codehilite:
        linenums: true
    - footnotes
    - meta
    - sane_lists
    - toc:
       permalink: true
       toc_depth: 3
    - pymdownx.superfences
